# Generated by Django 2.2.6 on 2019-10-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20191007_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='objects_image',
        ),
        migrations.RemoveField(
            model_name='object',
            name='map',
        ),
        migrations.RemoveField(
            model_name='object',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='object',
            name='y_position',
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Map')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Object')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='objects',
            field=models.ManyToManyField(through='maps.Layout', to='maps.Object'),
        ),
    ]
